language: ruby
rvm:
- 2.3.0
cache: bundler
addons:
  postgresql: '9.3'
script:
- bundle exec rake db:setup
- bundle exec rake db:test:prepare
- bundle exec rake db:fixtures:load
- bundle exec rake test
sudo: false
env:
- DATABASE_URL=postgresql://localhost/travis_ci_test RAILS_ENV=test
