---
driver:
  name: vagrant
  synced_folders:
    - ["../", '/www/imiq-map/current']
  network:
    - ["private_network", {ip: "192.168.222.227"}]
provisioner:
  name: chef_solo

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[imiq-map::default]
      - recipe[minitest-handler::default]
    attributes:
      imiq_map:
        account: "vagrant"
      postgresql:
        password:
          postgres: 'asdfasdfasdfasdf'
