#source 'https://supermarket.chef.io'
source :chef_server

group :integration do
  cookbook 'minitest-handler'
end

cookbook "chruby"

#cookbook 'yum-gina', git: "git@github.com:gina-alaska/yum-gina-cookbook"
cookbook 'unicorn', '~> 1.3.0'
cookbook "nginx", '~> 2.6.0'
cookbook "sudo", '~> 2.5.2'
cookbook 'postgresql'
cookbook 'database'
cookbook 'redisio', '~> 1.7.1'
cookbook 'postfix', '~> 3.6.0'
cookbook 'ruby-install'
cookbook 'ark', '~> 2.2.1'

metadata
